//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstantPhysics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstantPhysics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap angle {
            get {
                object obj = ResourceManager.GetObject("angle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap beginnermask {
            get {
                object obj = ResourceManager.GetObject("beginnermask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap billNyeTheFightingGuy {
            get {
                object obj = ResourceManager.GetObject("billNyeTheFightingGuy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap chemistry_atom_proton_electron_animation_17 {
            get {
                object obj = ResourceManager.GetObject("chemistry-atom-proton-electron-animation-17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap convexLens {
            get {
                object obj = ResourceManager.GetObject("convexLens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap emWave {
            get {
                object obj = ResourceManager.GetObject("emWave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap expertmask {
            get {
                object obj = ResourceManager.GetObject("expertmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap georgeNewtonLawThree {
            get {
                object obj = ResourceManager.GetObject("georgeNewtonLawThree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose and click on the definiton for .
        /// </summary>
        public static string L1Q3 {
            get {
                return ResourceManager.GetString("L1Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image is placed between the focus point and a distance twice that of the focus point. What properties will the image have?.
        /// </summary>
        public static string L2Q1 {
            get {
                return ResourceManager.GetString("L2Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick the true statements about Electromagnetic Waves..
        /// </summary>
        public static string L2Q2 {
            get {
                return ResourceManager.GetString("L2Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type of vision problem that involves a person being unable to focus there eyes on far away objects is called myopia (short sighted).
        ///What is the scientific name for the condition in which the person is unable to focus on close objects?.
        /// </summary>
        public static string L2Q3 {
            get {
                return ResourceManager.GetString("L2Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mainLogo {
            get {
                object obj = ResourceManager.GetObject("mainLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap newtonBall {
            get {
                object obj = ResourceManager.GetObject("newtonBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object either remains at rest or continues to move at a constant velocity, unless acted upon by a force..
        /// </summary>
        public static string NewtonLawOne {
            get {
                return ResourceManager.GetString("NewtonLawOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When one body exerts a force on a second body, the second body simultaneously exerts a force equal in magnitude and opposite in direction on the first body..
        /// </summary>
        public static string NewtonLawThree {
            get {
                return ResourceManager.GetString("NewtonLawThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The sum of the forces F on an object is equal to the mass m of that object multiplied by the acceleration a of the object: F = ma..
        /// </summary>
        public static string NewtonLawTwo {
            get {
                return ResourceManager.GetString("NewtonLawTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap realexpertmask {
            get {
                object obj = ResourceManager.GetObject("realexpertmask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shodinger {
            get {
                object obj = ResourceManager.GetObject("shodinger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sight {
            get {
                object obj = ResourceManager.GetObject("sight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap weirdIssacYankavic {
            get {
                object obj = ResourceManager.GetObject("weirdIssacYankavic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
